services:

  backend:
    build:
      context: ../backend
      dockerfile: backend.Dockerfile
    container_name: sgh-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: sgh_user
      POSTGRES_PASSWORD: sgh_password
      POSTGRES_DB: sgh_db
      POSTGRES_PORT: 5432
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: frontend.Dockerfile
    container_name: sgh-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15-alpine
    container_name: sgh-db
    environment:
      POSTGRES_USER: sgh_user
      POSTGRES_PASSWORD: sgh_password
      POSTGRES_DB: sgh_db
    ports:
      - "5432:5432"
    restart: always
